version: '2'
services:
    web:
        container_name: dev-axonivy-com-web
        build: ./docker/apache
        volumes:
            - ./:/var/www/html
            - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - 80:80